# Generated by Django 4.2.11 on 2026-04-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['elective__name', 'student__cgpa'],
            },
        ),
    ]
