# Generated by Django 4.2.11 on 2026-04-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electives', '0001_initial'),
        ('allotment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='elective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='electives.elective'),
        ),
    ]
