# Generated by Django 4.2.11 on 2026-04-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_seats', models.PositiveIntegerField(default=30)),
                ('available_seats', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, '1st Choice'), (2, '2nd Choice'), (3, '3rd Choice')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='electives.elective')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
